src/carla_ros_bridge/camera.py
- replace for-loop conversion with vectorized
- apply scaling to meters
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/11)
=> Fixes for depth conversion

Readme.md
I fixed `Readme.md` to run CARLA simulator for ros-bridge(related issue is https://github.com/carla-simulator/ros-bridge/issues/32).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/37)
=> fixed Readme.md

src/carla_ros_bridge/gnss.py, src/carla_ros_bridge/sensor.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/39)
=> Add handling of a GNSS Sensor

CHANGELOG.md, src/carla_ros_bridge/ego_vehicle.py, src/carla_ros_bridge/gnss.py
- support simple-pid 0.1.5
- cleanup code of Gnss Sensor (remove special tf transformation)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/44)
Fixes #42
=> Fix division by zero issue

client.launch
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/54)
=> Allow setting host, port and ego vehicle name as command line arguments

LICENSE, msg/CarlaVehicleControl.msg, msg/EgoVehicleControlCurrent.msg, msg/EgoVehicleControlInfo.msg, msg/EgoVehicleControlMaxima.msg, msg/EgoVehicleControlState.msg, msg/EgoVehicleControlTarget.msg, src/carla_ros_bridge/actor.py, src/carla_ros_bridge/actor_id_registry.py, src/carla_ros_bridge/bridge.py, src/carla_ros_bridge/bridge_with_rosbag.py, src/carla_ros_bridge/camera.py, src/carla_ros_bridge/child.py, src/carla_ros_bridge/client.py, src/carla_ros_bridge/ego_vehicle.py, src/carla_ros_bridge/gnss.py, src/carla_ros_bridge/lidar.py, src/carla_ros_bridge/map.py, src/carla_ros_bridge/parent.py, src/carla_ros_bridge/physics.py, src/carla_ros_bridge/sensor.py, src/carla_ros_bridge/spectator.py, src/carla_ros_bridge/traffic.py, src/carla_ros_bridge/transforms.py, src/carla_ros_bridge/vehicle.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/55)
=> Reworked copyright notice

carla_ackermann_control/src/carla_ackermann_control/carla_control_physics.py, carla_ros_bridge/msg/CarlaEgoVehicleControl.msg, carla_ros_bridge/src/carla_ros_bridge/ego_vehicle.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/65)
=> Add gear and manual_gear_shift to vehicle_status

carla_ros_bridge/src/carla_ros_bridge/bridge.py
resolves #62
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/66)
=> Fix bridge init of locks

carla_ros_bridge/src/carla_ros_bridge/object_sensor.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/70)
=> Add missing file

carla_ros_bridge/src/carla_ros_bridge/ego_vehicle.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/72)
=> Reenable sending of vehicle_status/info

carla_ros_bridge/launch/carla_ros_bridge_with_rviz.launch
carla_ros_bridge_with_rviz.launch was still calling client.launch which was renamed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/71)
=> Fixed behavior of carla_ros_bridge_with_rviz.launch

carla_ros_bridge/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/75)
=> CMakeLists: Remove duplicate installation of launch-files

carla_ros_bridge/src/carla_ros_bridge/ego_vehicle.py, carla_ros_bridge/src/carla_ros_bridge/parent.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/76)
=> Fix cleanup

carla_ros_bridge/src/carla_ros_bridge/sensor.py
'beeing' -> 'being'
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/77)
=> Minor typo fix

carla_ros_bridge/CMakeLists.txt, carla_ros_bridge/package.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/79)
=> Fix CMakeLists: Add derived_object_msgs as dependency

CHANGELOG.md, README.md, carla_ros_bridge/CMakeLists.txt, carla_ros_bridge/msg/CarlaCollisionEvent.msg, carla_ros_bridge/src/carla_ros_bridge/collision_sensor.py, carla_ros_bridge/src/carla_ros_bridge/sensor.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/78)
=> Add collision sensor

carla_ros_bridge/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/80)
=> Fix message generation dependencies

.gitignore, carla_ego_vehicle/CMakeLists.txt, carla_waypoint_publisher/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/88)
=> Add missing cmakelists

README.md, carla_ego_vehicle/src/carla_ego_vehicle/carla_ego_vehicle_base.py, carla_ego_vehicle/src/carla_ego_vehicle/carla_ros_manual_control.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/89)
=> Support custom lidar attributes

carla_ego_vehicle/launch/carla_ego_vehicle.launch, carla_ego_vehicle/src/carla_ego_vehicle/carla_ego_vehicle.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/103)
=> carla_ego_vehicle: Support initial spawn point

.pylintrc, carla_ackermann_control/src/carla_ackermann_control/carla_ackermann_control_node.py, carla_ego_vehicle/src/carla_ego_vehicle/carla_ego_vehicle.py, carla_ros_bridge/src/carla_ros_bridge/camera.py, carla_ros_bridge/src/carla_ros_bridge/child.py, carla_ros_bridge/src/carla_ros_bridge/collision_sensor.py, carla_ros_bridge/src/carla_ros_bridge/gnss.py, carla_ros_bridge/src/carla_ros_bridge/lane_invasion_sensor.py, carla_ros_bridge/src/carla_ros_bridge/lidar.py, carla_ros_bridge/src/carla_ros_bridge/parent.py, carla_waypoint_publisher/src/carla_waypoint_publisher/carla_waypoint_publisher.py
Result: 10.0 out of 10.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/107)
=> Fixed pylint warnings

.travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/108)
=> Added Travis jobs for pylint, autopep, and basic install

carla_ego_vehicle/launch/carla_ego_vehicle.launch, carla_ego_vehicle/src/carla_ego_vehicle/carla_ego_vehicle.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/109)
=> Cleanup spawn point handling in carla_ego_vehicle

CHANGELOG.md, carla_msgs/msg/CarlaEgoVehicleInfo.msg, carla_ros_bridge/src/carla_ros_bridge/ego_vehicle.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/112)
=> Add carla id to CarlaEgoVehicleInfo datatype

README.md
Relevant for #106
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/113)
=> Update object sensor doc

carla_manual_control/src/carla_manual_control/carla_manual_control.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/121)
=> Manual control: Set window caption

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/131)
=> Prepare release 0.9.5.1

.travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/132)
=> Updated ROS package key for Travis

CHANGELOG.md, README.md, carla_ros_bridge/src/carla_ros_bridge/ego_vehicle.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/129)
=> Support twist_cmd

carla_ros_bridge/CMakeLists.txt
Renamed client.py to bridge.py for install section
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/138)
=> Fixed carla_ros_bridge CMakeLists.txt

CHANGELOG.md, carla_ego_vehicle/config/sensors.json, carla_ego_vehicle/src/carla_ego_vehicle/carla_ego_vehicle.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/139)
=> carla_ego_vehicle: support sensor_tick within camera/lidar definition

carla_ego_vehicle/src/carla_ego_vehicle/carla_ego_vehicle.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/142)
=> carla_ego_vehicle: Make sensor_tick optional

carla_ego_vehicle/src/carla_ego_vehicle/carla_ego_vehicle.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/143)
=> carla_ego_vehicle: Make sensor_tick optional in lidar

carla_ackermann_control/src/carla_ackermann_control/carla_control_physics.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/145)
=> carla_ackermann_control: Fix wheel steer_angle naming

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/146)
=> Remove documentation for obsolete rosbag feature

carla_ros_bridge/src/carla_ros_bridge/ego_vehicle.py, carla_ros_bridge/src/carla_ros_bridge/vehicle.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/149)
=> Fix vehicle tfs

carla_ros_bridge/config/settings.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/151)
=> Synchronous mode is disabled by default

README.md, carla_manual_control/src/carla_manual_control/carla_manual_control.py, carla_msgs/msg/CarlaStatus.msg, carla_ros_bridge/config/settings.yaml, carla_ros_bridge/src/carla_ros_bridge/bridge.py, carla_ros_bridge/src/carla_ros_bridge/carla_status_publisher.py, carla_ros_bridge/src/carla_ros_bridge/ego_vehicle.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/160)
=> Update to Python API 0.9.6

carla_ros_bridge/launch/carla_ros_bridge.launch
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/166)
=> configure sync mode options via launch file arguments (#164)

CHANGELOG.md, README.md, carla_ego_vehicle/src/carla_ego_vehicle/carla_ego_vehicle.py, carla_infrastructure/src/carla_infrastructure/carla_infrastructure.py, carla_msgs/CMakeLists.txt, carla_msgs/msg/CarlaWorldInfo.msg, carla_ros_bridge/src/carla_ros_bridge/bridge.py, carla_ros_bridge/src/carla_ros_bridge/world_info.py, carla_ros_bridge/test/ros_bridge_client.py, carla_waypoint_publisher/src/carla_waypoint_publisher/carla_waypoint_publisher.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/170)
=> Only spawn ego vehicle if world is available

carla_ros_bridge/launch/carla_ros_bridge.launch, carla_ros_bridge/launch/carla_ros_bridge_with_example_ego_vehicle.launch, carla_ros_bridge/src/carla_ros_bridge/bridge.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/171)
=> Use same parameter approach for world-loading

carla_manual_control/src/carla_manual_control/carla_manual_control.py, carla_ros_bridge/src/carla_ros_bridge/bridge.py
TransformListener was called before initialization
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/172)
=> Fix race condition

CHANGELOG.md, README.md, carla_ego_vehicle/launch/carla_example_ego_vehicle.launch, carla_ros_bridge/launch/carla_ros_bridge_with_example_ego_vehicle.launch, carla_ros_bridge/src/carla_ros_bridge/bridge.py, carla_ros_bridge/src/carla_ros_bridge/debug_helper.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/176)
=> Support debug markers

CHANGELOG.md, README.md, carla_ros_bridge/src/carla_ros_bridge/ego_vehicle.py, carla_ros_bridge/src/carla_ros_bridge/traffic_participant.py, carla_ros_bridge/src/carla_ros_bridge/vehicle.py, carla_ros_bridge/src/carla_ros_bridge/walker.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/180)
=> Publish odometry for all traffic participants

carla_ros_bridge/src/carla_ros_bridge/debug_helper.py
This fixes then problem mentioned in https://github.com/carla-simulator/ros-bridge/issues/173#issuecomment-521069888
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/182)
=> Fix y coordinate in debug helper

carla_ros_bridge/src/carla_ros_bridge/debug_helper.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/183)
=> Code cleanup

carla_ros_bridge/launch/carla_ros_bridge_with_example_ego_vehicle.launch, pcl_recorder/launch/pcl_recorder.launch, pcl_recorder/src/PclRecorder.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/184)
=> Support different ego vehicle rolenames in pclrecorder

carla_ego_vehicle/README.md, carla_ego_vehicle/launch/carla_ego_vehicle.launch, carla_ego_vehicle/src/carla_ego_vehicle/carla_ego_vehicle.py
Use spawn_ego_vehicle parameter (set to false) to connect to an existing
ego vehicle.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/201)
=> Added possibility to connect to an existing ego vehicle

docker/Dockerfile
* Fixed docker build
* Use catkin tools to build the container
* Support ros melodic and kinetic
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/202)
=> Docker fixes and improvements

carla_ackermann_control/package.xml
Adding a build_depend for ackermann_msgs in carla_ackermann_control.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/211)
=> Added build dependency for ackermann_msgs

carla_ackermann_control/package.xml, carla_ros_bridge/package.xml, rqt_carla_control/package.xml
Added build dependencies in carla_ackermann_control, carla_ros_bridge, and rqt_carla_control packages.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/212)
=> Added build dependencies in multiple packages

carla_ego_vehicle/config/sensors.json, carla_ego_vehicle/src/carla_ego_vehicle/carla_ego_vehicle.py, carla_infrastructure/src/carla_infrastructure/carla_infrastructure.py, carla_ros_bridge/src/carla_ros_bridge/bridge.py, carla_ros_bridge/src/carla_ros_bridge/imu.py, carla_ros_bridge/test/ros_bridge_client.py
Implemented IMUSensor class for the integration of newly introduced IMU sensors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/215)
=> Integration of recently introduced IMU Sensor 

README.md, carla_ego_vehicle/config/sensors.json, carla_ego_vehicle/src/carla_ego_vehicle/carla_ego_vehicle.py, carla_infrastructure/src/carla_infrastructure/carla_infrastructure.py, carla_ros_bridge/CMakeLists.txt, carla_ros_bridge/package.xml, carla_ros_bridge/src/carla_ros_bridge/bridge.py, carla_ros_bridge/src/carla_ros_bridge/radar.py, carla_ros_bridge/test/ros_bridge_client.py
Implemented Radar class for integrating Radar sensor in ros-bridge.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/216)
=> Added support for Radar Sensor

carla_ego_vehicle/src/carla_ego_vehicle/carla_ego_vehicle.py
This resolves #219 by further checking for rgb camera specific attributes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/220)
=> Fix camera properties for depth and segmentation cameras

carla_ego_vehicle/src/carla_ego_vehicle/carla_ego_vehicle.py
Fix for the python format to make travis green
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/222)
=> fix python format issues

.pylintrc, CHANGELOG.md, README.md, carla_ackermann_control/README.md, carla_ackermann_control/setup.py, carla_ego_vehicle/README.md, carla_ego_vehicle/setup.py, carla_ego_vehicle/src/carla_ego_vehicle/carla_ego_vehicle.py, carla_infrastructure/README.md, carla_infrastructure/setup.py, carla_infrastructure/src/carla_infrastructure/carla_infrastructure.py, carla_manual_control/README.md, carla_manual_control/setup.py, carla_manual_control/src/carla_manual_control/carla_manual_control.py, carla_ros_bridge/setup.py, carla_ros_bridge/src/carla_ros_bridge/bridge.py, carla_ros_bridge/src/carla_ros_bridge/vehicle.py, carla_ros_bridge/test/ros_bridge_client.py, carla_waypoint_publisher/README.md, carla_waypoint_publisher/setup.py, pcl_recorder/README.md, rqt_carla_control/README.md, rqt_carla_control/setup.py
Code cleanup of the repository to make it more compliant with Codacy.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/224)
=> Fix Codacy

carla_ros_bridge.rdmanifest
Added carla_ros_bridge.manifest file for resolving Carla dependency in Package release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/226)
=> add manifest file for package release

carla_msgs/msg/CarlaEgoVehicleInfoWheel.msg, carla_ros_bridge/src/carla_ros_bridge/ego_vehicle.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/227)
=> Add additional wheel information

README.md, carla_msgs/CMakeLists.txt, carla_msgs/msg/CarlaTrafficLightStatus.msg, carla_msgs/msg/CarlaTrafficLightStatusList.msg, carla_ros_bridge/src/carla_ros_bridge/bridge.py, carla_ros_bridge/src/carla_ros_bridge/traffic.py, carla_ros_bridge/src/carla_ros_bridge/traffic_lights_sensor.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/229)
=> Add traffic lights sensor

CHANGELOG.md, carla_ros_bridge/launch/carla_ros_bridge_with_example_ego_vehicle.launch, carla_ros_bridge/src/carla_ros_bridge/camera.py, carla_ros_bridge/src/carla_ros_bridge/lidar.py, carla_ros_bridge/src/carla_ros_bridge/sensor.py, carla_twist_to_control/CMakeLists.txt, carla_twist_to_control/launch/carla_twist_to_control.launch, carla_twist_to_control/package.xml, carla_twist_to_control/setup.py, carla_twist_to_control/src/carla_twist_to_control/carla_twist_to_control.py
resolves #228
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/232)
=> Fix tf in synchronous mode, add twist to vehicle control node

carla_ad_demo/package.xml, pcl_recorder/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/247)
=> Fix some stuff for roslaunch check

CHANGELOG.md, README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/249)
=> Update changelog for 0.9.8 tag and cleanup README

carla_ad_demo/README.md
Replace := with = in the export SCENARIO_RUNNER_PATH
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/255)
=> typo in the second export

CHANGELOG.md, README.md, carla_ad_agent/src/carla_ad_agent/local_planner.py, carla_ego_vehicle/src/carla_ego_vehicle/carla_ego_vehicle.py, carla_ros_bridge/launch/carla_ros_bridge_with_example_ego_vehicle.launch, carla_ros_bridge/src/carla_ros_bridge/bridge.py, carla_twist_to_control/src/carla_twist_to_control/carla_twist_to_control.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/258)
=> Add support to load opendrive map

CHANGELOG.md, carla_ros_bridge/src/carla_ros_bridge/actor.py, carla_ros_bridge/src/carla_ros_bridge/traffic_participant.py, carla_ros_bridge/src/carla_ros_bridge/transforms.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/260)
=> Object-sensor: Fix object-twist (was published in vehicle-frame)

carla_ego_vehicle/src/carla_ego_vehicle/carla_ego_vehicle.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/261)
=> carla_ego_vehicle: fix check for duplicate sensor role names

CHANGELOG.md, carla_ackermann_control/launch/carla_ros_bridge_with_ackermann_control.launch, carla_ad_demo/launch/carla_ad_demo.launch, carla_ad_demo/launch/carla_ad_demo_with_rviz.launch, carla_ego_vehicle/launch/carla_ego_vehicle.launch, carla_ego_vehicle/launch/carla_example_ego_vehicle.launch, carla_ego_vehicle/src/carla_ego_vehicle/carla_ego_vehicle.py, carla_infrastructure/launch/carla_infrastructure.launch, carla_infrastructure/src/carla_infrastructure/carla_infrastructure.py, carla_ros_bridge/config/settings.yaml, carla_ros_bridge/launch/carla_ros_bridge.launch, carla_ros_bridge/launch/carla_ros_bridge_with_example_ego_vehicle.launch, carla_ros_bridge/src/carla_ros_bridge/bridge.py, carla_spectator_camera/launch/carla_spectator_camera.launch, carla_spectator_camera/src/carla_spectator_camera/carla_spectator_camera.py, carla_waypoint_publisher/launch/carla_waypoint_publisher.launch, carla_waypoint_publisher/src/carla_waypoint_publisher/carla_waypoint_publisher.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/264)
=> Added Timeout ROS-Parameter for CARLA Server communication

CreateROSbridgeDebian.sh, README.md, packaging/CreateROSbridgeDebian.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/265)
=> Adding script for creating debian package for carla-ros-bridge packages

CHANGELOG.md, README.md, carla_ad_agent/src/carla_ad_agent/carla_ad_agent.py, carla_ad_demo/launch/carla_ad_demo_with_rviz.launch, carla_ego_vehicle/src/carla_ego_vehicle/carla_ego_vehicle.py, carla_ros_bridge/launch/carla_ros_bridge.launch, carla_ros_bridge/src/carla_ros_bridge/actor.py, carla_ros_bridge/src/carla_ros_bridge/bridge.py, carla_ros_scenario_runner/src/carla_ros_scenario_runner/carla_ros_scenario_runner.py, carla_ros_scenario_runner/src/carla_ros_scenario_runner/scenario_runner_runner.py, carla_spectator_camera/src/carla_spectator_camera/carla_spectator_camera.py, carla_waypoint_publisher/src/carla_waypoint_publisher/carla_waypoint_publisher.py
- improve version checking
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/270)
=> Support carla 0.9.9

carla_ros_bridge/src/carla_ros_bridge/bridge.py
fixes #290 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/291)
=> Fix version check

carla_ros_bridge/src/carla_ros_bridge/imu.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/328)
=> Cleanup imports

carla_ros_bridge/src/carla_ros_bridge/bridge.py, carla_ros_bridge/src/carla_ros_bridge/rss_sensor.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/337)
=> Add rss sensor

carla_ad_demo/launch/carla_ad_demo.launch, carla_ad_demo/launch/carla_ad_demo_with_scenario.launch, carla_ego_vehicle/launch/carla_ego_vehicle.launch, carla_ego_vehicle/launch/carla_example_ego_vehicle.launch, carla_ego_vehicle/src/carla_ego_vehicle/carla_ego_vehicle.py, carla_infrastructure/launch/carla_infrastructure.launch, carla_infrastructure/src/carla_infrastructure/carla_infrastructure.py, carla_ros_bridge/config/settings.yaml, carla_ros_bridge/launch/carla_ros_bridge_with_example_ego_vehicle.launch, carla_spectator_camera/launch/carla_spectator_camera.launch, carla_spectator_camera/src/carla_spectator_camera/carla_spectator_camera.py, carla_waypoint_publisher/launch/carla_waypoint_publisher.launch, carla_waypoint_publisher/src/carla_waypoint_publisher/carla_waypoint_publisher.py
Default timeout increased to 10s to avoid `ros-bridge` node crashing when changing map.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/343)
=> Increase timeout

Makefile, README.md, carla_ego_vehicle/src/carla_ego_vehicle/carla_ego_vehicle.py, carla_ros_bridge/src/carla_ros_bridge/walker.py, ros_compatibility/__init__.py, ros_compatibility/src/ros_compatibility/__init__.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/351)
=> walker: add prefix + update doc/format

requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/354)
=> Freeze cmake-format version

.gitignore
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/353)
=> add some editor config folders to the gitignore

carla_ad_agent/src/carla_ad_agent/agent.py, carla_ad_agent/src/carla_ad_agent/basic_agent.py, carla_ad_agent/src/carla_ad_agent/carla_ad_agent.py, carla_ad_agent/src/carla_ad_agent/local_planner.py, carla_manual_control/src/carla_manual_control/carla_manual_control.py, carla_ros_bridge/src/carla_ros_bridge/bridge.py, carla_ros_bridge/src/carla_ros_bridge/lidar.py, carla_ros_scenario_runner/src/carla_ros_scenario_runner/carla_ros_scenario_runner.py, carla_ros_scenario_runner/src/carla_ros_scenario_runner/ros_vehicle_control.py, carla_ros_scenario_runner/src/carla_ros_scenario_runner/scenario_runner_runner.py
Fix one feature required for python3
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/352)
=> Python 3 Support

requirements.txt
I had to install the python package networkx to run the ros-bridge, so I added it to requirements.txt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/362)
=> added networkx in requirements.txt

docker/run.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/370)
=> Fix codacy issue

.travis.yml, docker/Dockerfile, pcl_recorder/CMakeLists.txt, rviz_carla_plugin/CMakeLists.txt
This contains some first contributions for supporting ros noetic. Current status
* Missing packages
* Carla python API for python 3.8
* Ideally install over PiPy
* Currently the build for python 3.8 fails -> open PR in https://github.com/carla-simulator/carla/pull/2857
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/323)
=> Supporting ros noetic

carla_ego_vehicle/src/carla_ego_vehicle/carla_ego_vehicle.py
Added missing `sensor_tick` property to IMU, GNSS and Radar.
FIxes https://github.com/carla-simulator/carla/issues/3035
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/369)
=> Added missing sensor_tick property to IMU, GNSS and Radar

carla_ros_bridge/src/carla_ros_bridge/ego_vehicle.py
Updated `set_velocity` to `set_target_velocity` (https://github.com/carla-simulator/carla/pull/3335)
This should not be merged until `0.9.10` is released.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/374)
=> [PythonAPI] Update set_velocity to set_target_velocity

carla_ad_agent/CMakeLists.txt, carla_ad_agent/package.xml, carla_ad_agent/setup.cfg, carla_ad_agent/setup.py, carla_ad_agent/src/carla_ad_agent/agent.py, carla_ad_agent/src/carla_ad_agent/basic_agent.py, carla_ad_agent/src/carla_ad_agent/carla_ad_agent.py, carla_ad_agent/src/carla_ad_agent/local_planner.py, carla_ad_agent/src/carla_ad_agent/vehicle_pid_controller.py, carla_ad_demo/CMakeLists.txt, carla_ad_demo/launch/carla_ad_demo.launch.py, carla_ad_demo/package.xml, carla_ad_demo/setup.py, carla_waypoint_publisher/CMakeLists.txt, carla_waypoint_publisher/package.xml, carla_waypoint_publisher/setup.cfg, carla_waypoint_publisher/setup.py, carla_waypoint_publisher/src/carla_waypoint_publisher/carla_waypoint_publisher.py, carla_waypoint_types/CMakeLists.txt, carla_waypoint_types/package.xml, mixin/skip.mixin, ros_compatibility/src/ros_compatibility/ros_compatible_node.py
ROS2 support added to the following packages:
- carla_ad_agent
- carla_waypoint_types
- carla_waypoint_publisher
- carla_ad_demo (partially)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/382)
=> Ros2 support ad agent

docker/Dockerfile.eloquent
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/383)
=> Disable rosdep install for eloquent

carla_ad_agent/src/carla_ad_agent/basic_agent.py, carla_ad_demo/config/FollowLeadingVehicle.xosc, carla_ros_scenario_runner/CMakeLists.txt, carla_ros_scenario_runner/launch/carla_ros_scenario_runner.launch, carla_ros_scenario_runner/launch/carla_ros_scenario_runner.launch.py, carla_ros_scenario_runner/package.xml, carla_ros_scenario_runner/setup.cfg, carla_ros_scenario_runner/setup.py, carla_ros_scenario_runner/src/carla_ros_scenario_runner/application_runner.py, carla_ros_scenario_runner/src/carla_ros_scenario_runner/carla_ros_scenario_runner_node.py, carla_ros_scenario_runner/src/carla_ros_scenario_runner/ros_vehicle_control.py, carla_ros_scenario_runner/src/carla_ros_scenario_runner/scenario_runner_runner.py, carla_ros_scenario_runner_types/CMakeLists.txt, carla_ros_scenario_runner_types/package.xml
Port of ros_scenario_runner to ROS2!
Some things to be noted:
- I used the application_runner class to launch the controller in ROS2, it's not running directly the launchfile through ROS2's LaunchService
- I renamed carla_ros_scenario_runner.py to carla_ros_scenario_runner_node.py, to avoid an import problem in ROS2
- I had to modifiy some camera parameters in _carla_ego_vehicle/config/sensors.json_, to use carla  9.10. These modifs were copied from a recent commit in _ros_bridge/master_, so I didn't commit them here.
- It doesn't work with the launch file _carla_ad_demo/carla_ad_demo_with_scenario.launch.py_ yet, as this requires rviz
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> Scenario runner ros2

carla_ad_agent/src/carla_ad_agent/carla_ad_agent.py, carla_ros_scenario_runner/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/388)
=> New launchfiles and fix

carla_ego_vehicle/src/carla_ego_vehicle/carla_ego_vehicle.py, ros_compatibility/src/ros_compatibility/ros_compatible_node.py
This PR improves error handling of the `carla_ego_vehicle` node. Previously it did swallow some errors and made it hard to find out what's going on. As a bonus side effect it unifies the ROS1/2 code paths for waiting for the world to become available.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/381)
=> [ROS2] Fix error handling in carla_ego_vehicle

carla_infrastructure/CMakeLists.txt, carla_infrastructure/launch/carla_infrastructure.launch, carla_infrastructure/launch/carla_infrastructure.launch.py, carla_infrastructure/package.xml, carla_infrastructure/setup.cfg, carla_infrastructure/setup.py, carla_infrastructure/src/carla_infrastructure/carla_infrastructure.py
Port of carla_infrastructure to ros2, tested with both rviz and rviz2 in ros and ros2 respectively.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/392)
=> Carla infrastructure ros2

carla_ego_vehicle/src/carla_ego_vehicle/carla_ego_vehicle.py, carla_ros_bridge/src/carla_ros_bridge/camera.py, carla_ros_bridge/src/carla_ros_bridge/sensor.py, carla_walker_agent/CMakeLists.txt, carla_walker_agent/launch/carla_walker_agent.launch.py, carla_walker_agent/package.xml, carla_walker_agent/setup.cfg, carla_walker_agent/setup.py, carla_walker_agent/src/carla_walker_agent/carla_walker_agent.py, carla_waypoint_publisher/launch/carla_waypoint_publisher.launch.py
Port of carla_walker_agent to ROS2
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/393)
=> Walker agent ros2

carla_ad_demo/config/carla_ad_demo.rviz
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/402)
=> fixed camera topic name

CHANGELOG.md, README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/409)
=> update readme and changelog with ROS noetic support

carla_ros_bridge/src/carla_ros_bridge/lidar.py, carla_ros_scenario_runner/src/carla_ros_scenario_runner/carla_ros_scenario_runner.py
resolves #400
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/410)
=> Fix lidar parsing in noetic

packaging/CreateROSbridgeDebian.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/411)
=> Read packaging version from latest git tag

.github/workflows/ci.yml, .travis.yml, README.md
* To speedup the CI build and use the better github integration I moved the check to github actions
* I added some badges to show the status in the readme
* I also plan to move the ros build but this will follow in another PR
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/413)
=> Ci refactoring

.github/workflows/ci.yml, .travis.yml, README.md, packaging/install_dependencies.sh
* Add installation script for dependencies
* Move ros ci job to github actions
* For now a draft, but I will rebase once #413 is merged
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/414)
=> Ci refactoring ros

carla_ego_vehicle/src/carla_ego_vehicle/carla_ego_vehicle.py, carla_ros_bridge/src/carla_ros_bridge/actor_factory.py, carla_ros_bridge/src/carla_ros_bridge/actor_list_sensor.py, carla_ros_bridge/src/carla_ros_bridge/bridge.py, carla_ros_bridge/src/carla_ros_bridge/marker_sensor.py, carla_ros_bridge/src/carla_ros_bridge/object_sensor.py, carla_ros_bridge/src/carla_ros_bridge/odom_sensor.py, carla_ros_bridge/src/carla_ros_bridge/opendrive_sensor.py, carla_ros_bridge/src/carla_ros_bridge/pseudo_actor.py, carla_ros_bridge/src/carla_ros_bridge/speedometer_sensor.py, carla_ros_bridge/src/carla_ros_bridge/tf_sensor.py, carla_ros_bridge/src/carla_ros_bridge/traffic_lights_sensor.py, carla_ros_bridge/src/carla_ros_bridge/traffic_participant.py, carla_ros_bridge/src/carla_ros_bridge/world_info.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/417)
=> Support GetBlueprints() service

carla_ego_vehicle/src/carla_ego_vehicle/carla_ego_vehicle.py, carla_ros_bridge/src/carla_ros_bridge/actor_control.py, carla_ros_bridge/src/carla_ros_bridge/actor_factory.py, carla_ros_bridge/src/carla_ros_bridge/bridge.py, carla_ros_bridge/src/carla_ros_bridge/ego_vehicle.py, carla_ros_bridge/src/carla_ros_bridge/pseudo_actor.py
Allow access to CARLA's set_transform() and set_target_velocity() from a topic.
This can be enabled for every actor.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/420)
=> Add pseudo  actor control

carla_ackermann_control/CMakeLists.txt, carla_ad_agent/CMakeLists.txt, carla_ad_demo/CMakeLists.txt, carla_ego_vehicle/CMakeLists.txt, carla_infrastructure/CMakeLists.txt, carla_manual_control/CMakeLists.txt, carla_ros_bridge/CMakeLists.txt, carla_ros_scenario_runner/CMakeLists.txt, carla_spectator_camera/CMakeLists.txt, carla_twist_to_control/CMakeLists.txt, carla_walker_agent/CMakeLists.txt, carla_waypoint_publisher/CMakeLists.txt, pcl_recorder/CMakeLists.txt
Hi, 
Fix build error when CATKIN_ENABLE_TESTING=OFF.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/424)
=> Fix build error when CATKIN_ENABLE_TESTING=OFF

Makefile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/427)
=> Ignore packaging/build from Makefile search path

carla_ad_demo/launch/carla_ad_demo.launch, carla_ad_demo/launch/carla_ad_demo_with_scenario.launch, carla_ros_bridge/config/settings.yaml, carla_ros_bridge/launch/carla_ros_bridge.launch, carla_ros_bridge/launch/carla_ros_bridge_with_example_ego_vehicle.launch, carla_ros_bridge/src/carla_ros_bridge/bridge.py, carla_ros_bridge/src/carla_ros_bridge/carla_status_publisher.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/434)
=> Added passive parameter

carla_ros_bridge/src/carla_ros_bridge/actor_factory.py, carla_ros_bridge/src/carla_ros_bridge/bridge.py, carla_spawn_objects/src/carla_spawn_objects/carla_spawn_objects.py, carla_spectator_camera/src/carla_spectator_camera/carla_spectator_camera.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/437)
=> Removed waiting for world info topic

carla_ackermann_control/src/carla_ackermann_control/carla_control_physics.py, carla_ad_agent/src/carla_ad_agent/agent.py, carla_ad_agent/src/carla_ad_agent/vehicle_pid_controller.py, carla_common/src/carla_common/transforms.py, carla_manual_control/src/carla_manual_control/carla_manual_control.py, carla_ros_bridge/src/carla_ros_bridge/camera.py, carla_ros_bridge/src/carla_ros_bridge/debug_helper.py, carla_ros_bridge/src/carla_ros_bridge/imu.py, carla_ros_bridge/src/carla_ros_bridge/lidar.py, carla_ros_bridge/src/carla_ros_bridge/speedometer_sensor.py, carla_spawn_objects/src/carla_spawn_objects/carla_spawn_objects.py, carla_spectator_camera/src/carla_spectator_camera/carla_spectator_camera.py, carla_waypoint_publisher/src/carla_waypoint_publisher/carla_waypoint_publisher.py, ros_compatibility/src/ros_compatibility/ros_compatible_node.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/447)
=> Ros2 transforms cleanup

carla_ros_bridge/src/carla_ros_bridge/actor_factory.py, carla_ros_bridge/src/carla_ros_bridge/bridge.py, carla_spawn_objects/src/carla_spawn_objects/carla_spawn_objects.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/446)
=> Fixed spawn bug

carla_ad_demo/config/carla_ad_demo_ros2.rviz
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/453)
=> error in rviz2 config file to show markers

ros_compatibility/src/ros_compatibility/ros_compatible_node.py
The _wait_for_one_message_ ros2 function in ros_compatibility seemed to have some problem, I re-wrote it getting a lot of inspiration from the equivalent one in rospy (https://github.com/ros/ros_comm/blob/noetic-devel/clients/rospy/src/rospy/client.py#L391). 
The mechanism that was used to count timeouts before was not really precise, and I switched to python _time_ functions (like in the rospy function).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/455)
=> improved wait_for_one_message ros2 function

carla_spawn_objects/src/carla_spawn_objects/carla_spawn_objects.py, ros_compatibility/src/ros_compatibility/ros_compatible_node.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/460)
=> Spawn object shutdown

carla_ad_agent/src/carla_ad_agent/agent.py, carla_ad_agent/src/carla_ad_agent/basic_agent.py, carla_ad_agent/src/carla_ad_agent/carla_ad_agent.py
carla_ad_agent now finishes cleanly. Tested with both ros1 and ros2 as well as async/sync modes.
Also removed a bug that was printing a lot of useless warnings when starting.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/461)
=> fix carla_ad_agent shutdown bug

carla_manual_control/src/carla_manual_control/carla_manual_control.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/464)
=> carla_manual_control: fix throttle/brake display

carla_ad_agent/src/carla_ad_agent/basic_agent.py, carla_ad_agent/src/carla_ad_agent/carla_ad_agent.py, carla_ad_demo/launch/carla_ad_demo.launch.py, carla_ros_bridge/src/carla_ros_bridge/actor_factory.py, carla_ros_bridge/src/carla_ros_bridge/bridge.py, carla_spawn_objects/src/carla_spawn_objects/carla_spawn_objects.py, carla_waypoint_publisher/src/carla_waypoint_publisher/carla_waypoint_publisher.py
Cleanup for error handling and cleanup when shutting down. I'm now able to shutdown cleanly (including destroying all objects) _almost_ in all cases.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/463)
=> more cleanup in bridge, spawn_object and agent

carla_ad_agent/src/carla_ad_agent/basic_agent.py, carla_ad_demo/launch/carla_ad_demo.launch.py, carla_manual_control/src/carla_manual_control/carla_manual_control.py, carla_spawn_objects/src/carla_spawn_objects/carla_spawn_objects.py, carla_waypoint_publisher/src/carla_waypoint_publisher/carla_waypoint_publisher.py, ros_compatibility/src/ros_compatibility/ros_compatible_node.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/466)
=> Some fixes

carla_manual_control/src/carla_manual_control/carla_manual_control.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/472)
=> removed unnecessary clock subcriber in manual control

carla_ackermann_control/launch/carla_ackermann_control.launch, carla_ackermann_control/launch/carla_ackermann_control.launch.py, carla_ackermann_control/src/carla_ackermann_control/carla_ackermann_control_node.py, carla_ros_bridge/src/carla_ros_bridge/bridge.py, carla_ros_scenario_runner/src/carla_ros_scenario_runner/application_runner.py, ros_compatibility/src/ros_compatibility/ros_compatible_node.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/480)
=> Some fix leaderboard

README.md, README.ros.md, README.ros2.md, carla_ad_agent/CMakeLists.txt, carla_ad_agent/README.md, carla_ad_agent/launch/carla_ad_agent.launch, carla_ad_agent/launch/carla_ad_agent.launch.py, carla_ad_agent/setup.py, carla_ad_agent/src/carla_ad_agent/agent.py, carla_ad_agent/src/carla_ad_agent/basic_agent.py, carla_ad_agent/src/carla_ad_agent/carla_ad_agent.py, carla_ad_agent/src/carla_ad_agent/local_planner.py, carla_ad_agent/src/carla_ad_agent/vehicle_pid_controller.py, carla_ad_demo/README.md, carla_ad_demo/launch/carla_ad_demo.launch, carla_ad_demo/launch/carla_ad_demo.launch.py, carla_ad_demo/launch/carla_ad_demo_with_scenario.launch, carla_ad_demo/launch/carla_ad_demo_with_scenario.launch.py, carla_ros_bridge/src/carla_ros_bridge/radar.py, carla_ros_scenario_runner/src/carla_ros_scenario_runner/application_runner.py, carla_ros_scenario_runner/src/carla_ros_scenario_runner/ros_vehicle_control.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/470)
=> new carla_ad_agent structure and tuned longitudinal controller

.gitmodules, README.md, README.ros.md, README.ros2.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/484)
=> Remove astuff_sensor_msgs submodule

README.md, README.ros.md, ros_compatibility/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/486)
=> some readme corrections

carla_common/CMakeLists.txt, carla_ros_bridge/src/carla_ros_bridge/bridge.py, carla_spawn_objects/src/carla_spawn_objects/carla_spawn_objects.py, carla_twist_to_control/src/carla_twist_to_control/carla_twist_to_control.py, ros_compatibility/src/ros_compatibility/ros_compatible_node.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/490)
=> [ROS1] Fix shutdown

carla_ros_bridge/launch/carla_ros_bridge_with_rviz.launch.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/496)
=> Rviz package name fixed

README.md, carla_ad_demo/launch/carla_ad_demo.launch, carla_ad_demo/launch/carla_ad_demo.launch.py, carla_ad_demo/launch/carla_ad_demo_with_scenario.launch, carla_ad_demo/launch/carla_ad_demo_with_scenario.launch.py, carla_ros_bridge/launch/carla_ros_bridge.launch, carla_ros_bridge/launch/carla_ros_bridge.launch.py, carla_ros_bridge/launch/carla_ros_bridge_with_example_ego_vehicle.launch, carla_ros_bridge/launch/carla_ros_bridge_with_example_ego_vehicle.launch.py, carla_ros_bridge/src/carla_ros_bridge/bridge.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/497)
=> [ROS2] Default sync mode

README.ros.md, README.ros2.md, carla_ad_agent/README.md, carla_ad_demo/README.md, carla_manual_control/README.md, carla_ros_scenario_runner/README.md, carla_spawn_objects/README.md, carla_twist_to_control/README.md, carla_waypoint_publisher/README.md, pcl_recorder/README.md, ros_compatibility/README.md, rviz_carla_plugin/README.md
* Use code blocks in main readme files to get syntax higliting
* Fix some typos
* Remove dplicated blank lines
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/514)
=> Readme improvements

carla_ros_bridge/src/carla_ros_bridge/camera.py, carla_ros_bridge/src/carla_ros_bridge/sensor.py
Fixes #511
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/516)
=> Fix camera TF orientation

carla_ros_bridge/src/carla_ros_bridge/ego_vehicle.py
ref #521
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/522)
=> fixed wheels position transform in VehicleInfo

carla_ros_bridge/src/carla_ros_bridge/ego_vehicle.py
Spawning vehicle stopped working for me in the latest version of the bridge.
```
[bridge-1] Exception in thread Thread-2:
[bridge-1] Traceback (most recent call last):
[bridge-1]   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[bridge-1]     self.run()
[bridge-1]   File "/usr/lib/python3.8/threading.py", line 870, in run
[bridge-1]     self._target(*self._args, **self._kwargs)
[bridge-1]   File "/work/ws/install/carla_ros_bridge/lib/python3.8/site-packages/carla_ros_bridge/bridge.py", line 297, in _synchronous_mode_update
[bridge-1]     self._update(frame, world_snapshot.timestamp.elapsed_seconds)
[bridge-1]   File "/work/ws/install/carla_ros_bridge/lib/python3.8/site-packages/carla_ros_bridge/bridge.py", line 338, in _update
[bridge-1] …
```
=> Fix matrix initialization in send_vehicle_msgs

carla_spawn_objects/launch/carla_example_ego_vehicle.launch.py, carla_spawn_objects/launch/set_initial_pose.launch.py, carla_spawn_objects/setup.py, carla_spawn_objects/src/carla_spawn_objects/carla_spawn_objects.py, carla_spawn_objects/src/carla_spawn_objects/set_initial_pose.py
Using new `roscomp` API and ported `set_initial_pose` node to ROS2
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/530)
=> Refactor carla spawn actors 

carla_manual_control/src/carla_manual_control/carla_manual_control.py, docs/carla_manual_control.md
Refactors manual control package
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/531)
=> Refactor manual control package

carla_ackermann_control/setup.cfg, carla_ad_agent/setup.cfg, carla_common/setup.cfg, carla_manual_control/setup.cfg, carla_ros_bridge/setup.cfg, carla_ros_scenario_runner/setup.cfg, carla_spawn_objects/setup.cfg, carla_twist_to_control/setup.cfg, carla_walker_agent/setup.cfg, carla_waypoint_publisher/setup.cfg, ros_compatibility/setup.cfg, rqt_carla_control/setup.cfg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/536)
=> Use underscores instead of dashes in setup.cfg

carla_ros_bridge/src/carla_ros_bridge/actor_control.py
Observable in the rviz visualization of the view-camera.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/537)
=> Fix tf for sensors that are moved by actor.pseudo.control

carla_ad_agent/launch/carla_ad_agent.launch, carla_ad_agent/launch/carla_ad_agent.launch.py, carla_ad_agent/src/carla_ad_agent/ad_agent.py, carla_ad_agent/src/carla_ad_agent/agent.py, carla_ad_agent/src/carla_ad_agent/local_planner.py, carla_ad_demo/config/FollowLeadingVehicle.xosc, carla_ad_demo/launch/carla_ad_demo.launch, carla_ad_demo/launch/carla_ad_demo.launch.py, carla_ros_scenario_runner/src/carla_ros_scenario_runner/application_runner.py, carla_ros_scenario_runner/src/carla_ros_scenario_runner/ros_vehicle_control.py, docs/carla_ad_agent.md
Until now a fixed target-speed was used in carla_ad_agent.
Additionally the QoSProfiles were fixed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/538)
=> Carla_ad_agent: Use target_speed from scenario

CHANGELOG.md, carla_ros_scenario_runner/src/carla_ros_scenario_runner/scenario_runner_runner.py
fixes #572
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/573)
=> Change trigger text for running scenario

carla_ackermann_control/src/carla_ackermann_control/carla_ackermann_control_node.py
carla_ackermann_control:
- fill header of output messages
- use simulated time to check for last received ackerman msg, otherwhise
no contol command is published anymore if frames in sync mode last for
too long
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/574)
=> carla_ackermann_control fill header and make sync mode robust

.github/workflows/ci.yml, install_dependencies.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/626)
=> Fix CI rosversion cmd missing

pcl_recorder/CMakeLists.txt, pcl_recorder/src/PclRecorderROS2.cpp, rviz_carla_plugin/CMakeLists.txt
This PR adds missing dependencies and changes deprecated API calls.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/617)
=> Added missing dependencies

carla_ros_bridge/launch/carla_ros_bridge_with_example_ego_vehicle.launch.py, carla_ros_bridge/test/ros_bridge_client_ros2_test.py, carla_spawn_objects/launch/carla_example_ego_vehicle.launch.py, carla_spawn_objects/launch/carla_spawn_objects.launch.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/625)
=> Remove empty launch args default_value (#622)
