carla-simulator/ros-bridge

- src/carla_ros_bridge/ego_vehicle.py
With this commit, the CARLA-ROS-bridge sends vehicle control commands to CARLA,
only when there is input from the ROS side.
Tested with CARLA 0.9.2 on Ubuntu 16.04
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/22)
> Send vehicle control commands only when reciving ROS input

- src/carla_ros_bridge/ego_vehicle.py
The last commit introduced an issue when using ROS ackermann_msgs to
control the vehicle through the ROS bridge in CARLA. This commit fixed
this issue.
Resolves Issue #27 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/31)
> Fixed issue of vehicle not moving despite ROS input is properly set

- src/carla_ros_bridge/ego_vehicle.py
- src/carla_ros_bridge/gnss.py
As get_num_connections() does not report a reliable value a timeout is used instead.
If no new control command was received within 3 seconds the carla client does not get updated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/46)
> EgoVehicle Ackermann Control: Only apply control if a ros publisher is connected

- carla_ros_bridge/launch/carla_ros_bridge_with_rviz.launch
The launch file that opens RViz has the wrong path to the base launch file. This diff fixes it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/74)
> [carla_ros_bridge] fix rviz launch file path

- carla_ackermann_control/package.xml
The `carla_ackermann_control` package is missing dependencies to `carla_ros_bridge`, which leads to build failures on a clean build (using catkin tools):
CMake Error at /opt/ros/melodic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
Could not find a package configuration file provided by "carla_ros_bridge"
with any of the following names:
carla_ros_bridgeConfig.cmake
carla_ros_bridge-config.cmake
Add the installation prefix of "carla_ros_bridge" to CMAKE_PREFIX_PATH or
set "carla_ros_bridge_DIR" to a directory containing one of the above
files.  If "carla_ros_bridge" provides a separate development package or
SDK, be sure it has been installed.
Call Stack (most recent call first):
CMakeLists.txt:5 (find_package)
The diff just adds all the CMake dependencies to `package.xml` as …
> [carla_ackermann_control] add dependencies to package.xml

- carla_ros_bridge/src/carla_ros_bridge/bridge.py
- carla_ros_bridge/src/carla_ros_bridge/sensor.py
- carla_waypoint_publisher/src/carla_waypoint_publisher/carla_waypoint_publisher.py
Following ROS specs towards tf2, tf_prefix it's
not supported in tf2.
This change allows packages like robot_localization
to work with ros-bridge, before that there where
a conflict between the frame_id names. Where
ros-bridge use "/map" and robot_localization
use "map".
Source: http://wiki.ros.org/tf2/Migration
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/117)
> Removing initial slash from frame_id names for tf

- carla_ros_bridge/launch/carla_ros_bridge.launch
Add some launch file arguments so that synchronous mode can be configured without touching the `ros-bridge` repo. This way external packages can configure the bridge as they need to. For example, I can define a custom launch file as:
```
<launch>
<include file="$(find carla_ros_bridge)/launch/carla_ros_bridge.launch">
<arg name="synchronous_mode" value="true"/>
<arg name="synchronous_mode_wait_for_vehicle_control_command" value="true"/>
<arg name="fixed_delta_seconds" value="0.1"/>
</include>
</launch>
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/164)
> configure sync mode options via launch file arguments

- CHANGELOG.md
- README.md
- carla_infrastructure/CMakeLists.txt
- carla_infrastructure/README.md
- carla_infrastructure/config/sensors.json
- carla_infrastructure/launch/carla_infrastructure.launch
- carla_infrastructure/package.xml
- carla_infrastructure/setup.py
- carla_infrastructure/src/carla_infrastructure/carla_infrastructure.py
- carla_ros_bridge/launch/carla_ros_bridge.launch
- carla_ros_bridge/src/carla_ros_bridge/bridge.py
This PR adds a ROS node that can spawn infrastructure sensors.
In addition, it is now also possible to reloaded the CARLA world via the ROS bridge by specifying the carla_town argument in the carla_ros_bridge.launch
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/168)
> Add infrastructure support

- carla_ros_bridge/src/carla_ros_bridge/transforms.py
According to the rotation convention in Unreal, https://github.com/carla-simulator/carla/issues/553#issuecomment-420652695, the rotation along the x-axis (roll) should keep the original sign from carla.
In the previous version 97a1258, the roll angle is in the opposite direction, which can be verified by driving a car half onto the curb.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/167)
> Fix roll bug in transforms

- carla_waypoint_publisher/README.md
carla_waypoint_ros_publisher.launch should be carla_waypoint_publisher.launch
because that's the only one in the folder I'm assuming it's the right one.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/210)
> change launch file name in README

- carla_ego_vehicle/config/sensors.json
Changed the noise attributes for IMU and GNSS Sensors to give out default ideal sensors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/230)
> Change attributes for Gnss and Imu Sensor

- carla_ros_scenario_runner/src/carla_ros_scenario_runner/scenario_runner_runner.py
In order to not run into a timeout while pausing the simulation, set scenario runner timeout to 1000000
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/250)
> Fix scenario runner timeout

- carla_ros_bridge/src/carla_ros_bridge/imu.py
All IMU sensors publish readings on one topic e.g. /carla/ego_vehicle/imu. The subject name should contain sensor role name as for other sensors. This change should resolve this issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/256)
> Add role name to imu topic

- CHANGELOG.md
- carla_ros_bridge/src/carla_ros_bridge/ego_vehicle.py
Replaced setting of quaternion x to 1.0 with w.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/299)
> Fixed ego_vehicle TF

- carla_ros_bridge/src/carla_ros_bridge/bridge.py
This PR fixes a crash of the bridge when an ego vehicle is used. The crash happens due to a faulty method call. The code in question is this:
https://github.com/carla-simulator/ros-bridge/blob/0a05b7fad550f90c25be9dc68bed92be0c0d5364/carla_ros_bridge/src/carla_ros_bridge/bridge.py#L444-L450
The parameter of `add_node` is of type `rclpy.node.Node`, but it is passed an `EgoVehicle` as argument, which is not a subtype of `Node`. The registration of the bridge node is already happening in `main()` by calling the `add_node` method there. Thus, I think removing the above lines should be fine.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/346)
> [ROS2] Fix crash when using an ego vehicle

- carla_ros_bridge/src/carla_ros_bridge/vehicle.py
This PR modifies the Vehicle class to publish valid ROS2 topics to stop them from crashing the bridge. It changes the topic under which vehicles are published to the schema `vehicle/vXXX` with a ‘v’ before the id. ROS2 requires topic tokens to not start with a number.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/349)
> [ROS2] Make Vehicle conform to topic naming rules

- carla_ros_bridge/src/carla_ros_bridge/actor.py
- carla_ros_bridge/src/carla_ros_bridge/vehicle.py
This PR changes two instances of `ColorRGBA` to be initialized with the proper type of values, by that preventing the bridge from crashing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/350)
> [ROS2] Fix attribute types of ColorRGBA instances

- README.md
The installation process of the debian package has been modified. Now, both packages (i.e., `carla-simulator` and `carla-ros-bridge`) are inside the same apt repository and all the future updates will be added in this same repository.
The installation process now is as follows:
```sh
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 1AF1527DE64CB8D9
sudo add-apt-repository "deb [arch=amd64] http://dist.carla.org/carla $(lsb_release -sc) main"
sudo apt-get update
sudo apt-get install carla-simulator
sudo apt-get install carla-ros-bridge
```
It is also possible to install specific versions:
```
sudo apt-get install carla-simulator=0.9.10-1
sudo apt-get install carla-ros-bridge=0.9.10-1
```
To install ROS bridge versions prior to 0.9.10, the older instructions should be followed. …
> Updated user installtion process

- .travis.yml
- README.md
- requirements.txt
I had to install manually the python packages pygame and transforms3d, so I added them to requirements.txt. I think rosdep should be able to install these, but it wasn't working.
I also added a ROS2 section in the documentation. The main reason was to note that the RMW implementation rmw_fastrtps_cpp should be used with ROS2, I initially was using rmw_connext_cpp and couldn't get the ros2 nodes running.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/365)
> Update ros2 requirements documentation

- carla_ros_bridge/src/carla_ros_bridge/traffic_participant.py
Classification certainty value modified from `1.0` to `255`. As specified in the message documentation (http://docs.ros.org/melodic/api/derived_object_msgs/html/msg/Object.html), the value has to be in the range `0-255`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/373)
> Fixed classification certainty value

- carla_ros_bridge/src/carla_ros_bridge/ego_vehicle.py
Acceleration is now in the `map` frame instead of the `ego_vehicle` frame as the header message states. 
Fixes: https://github.com/carla-simulator/ros-bridge/issues/325
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/378)
> Fixed acceleration frame

- carla_ros_bridge/src/carla_ros_bridge/gnss.py
This PR adds the `listen` call to the `gnss` sensor to register the callback.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/390)
> GNSS listen call

- carla_ros_bridge/src/carla_ros_bridge/camera.py
- carla_ros_bridge/src/carla_ros_bridge/sensor.py
In carla_ros_bridge the sensor class was inheriting from CompatibleNode, so a new ros node was created for each sensor in ros2. This was causing problems, as if one type of sensor was spawned several times, several nodes with same name were created.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/391)
> remove inheritance on CompatibleNode for sensor in carla_ros_bridge

- pcl_recorder/CMakeLists.txt
- pcl_recorder/include/PclRecorderROS2.h
- pcl_recorder/launch/pcl_recorder.launch.py
- pcl_recorder/package.xml
- pcl_recorder/src/PclRecorderROS2.cpp
- pcl_recorder/src/mainROS2.cpp
Ported pcl_recorder to ROS2:
- The separation between ROS1 and ROS2 is made in the CMakeList.txt file, two different sets of source code are used 
- The ROS2 code doesn't depend on pcl_ros (not available for ROS2) but directly on pcl
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/395)
> ported pcl_recorder to ros2

- carla_ros_bridge/launch/carla_ros_bridge.launch.py
- carla_ros_bridge/launch/carla_ros_bridge_with_example_ego_vehicle.launch
- carla_ros_bridge/launch/carla_ros_bridge_with_example_ego_vehicle.launch.py
- carla_ros_bridge/src/carla_ros_bridge/bridge.py
- rqt_carla_control/CMakeLists.txt
- rqt_carla_control/package.xml
- rqt_carla_control/setup.cfg
- rqt_carla_control/setup.py
- rqt_carla_control/src/rqt_carla_control/rqt_carla_control.py
Port of rqt_carla_control to ROS2.
- uses CompatibleNode for ROS1/ROS2 compatibility
- in ROS2, creates a thread to spin (there might be a more elegant way to do this)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/397)
> port of rqt plugin to ros2

- carla_ad_demo/config/carla_ad_demo.rviz
The Rviz configuration file was subscribed to the wrong camera topic name. Updated `SENSOR_ROLE_NAME` to `view`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/401)
> Fixed camera topic name

- carla_ad_demo/config/carla_ad_demo_ros2.rviz
- carla_ad_demo/launch/carla_ad_demo_with_scenario.launch.py
- carla_ad_demo/package.xml
- carla_ad_demo/setup.py
- carla_ros_bridge/src/carla_ros_bridge/ego_vehicle.py
- carla_spectator_camera/CMakeLists.txt
- carla_spectator_camera/launch/carla_spectator_camera.launch.py
- carla_spectator_camera/package.xml
- carla_spectator_camera/setup.cfg
- carla_spectator_camera/setup.py
- carla_spectator_camera/src/carla_spectator_camera/carla_spectator_camera.py
- carla_twist_to_control/CMakeLists.txt
- carla_twist_to_control/launch/carla_twist_to_control.launch.py
- carla_twist_to_control/setup.py
- rviz_carla_plugin/CMakeLists.txt
- rviz_carla_plugin/package.xml
- rviz_carla_plugin/plugin_description_ros2.xml
- rviz_carla_plugin/src/carla_control_panel_ROS2.cpp
- rviz_carla_plugin/src/carla_control_panel_ROS2.h
Port of the rviz_carla_plugin to rviz/ros2:
The main source files that define the carla panel (_carla_control_panel.cpp/h_) remain unchanged, but when using ROS2, the CMakelists.txt uses the new files _carla_control_panel_ROS2.cpp/h_ to build the plugin library.
The only thing missing when using this with ros2, is the Time panel in rviz2, that was used in ros1 to display simulation time, real time, etc... This plugin is not available in the eloquent rviz2 library, but it probably will be in future distributions, as I saw it was already implemented in the master branch.
Apart from that, running scenarios, moving the spectator camera, and using the DriveWidget to manually control the ego vehicle should work. I also finished to configure the carla_ad_demo package, so the …
> rviz_carla_plugin port to rviz2/ros2

- carla_ros_bridge/src/carla_ros_bridge/bridge.py
- carla_spectator_camera/src/carla_spectator_camera/carla_spectator_camera.py
We are now using services to spawn and destroy the spectator camera. The tf data is now published correctly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/435)
> Using services to spawn spectator camera

- carla_ros_bridge/src/carla_ros_bridge/actor_factory.py
- first two commits to fix the update thread that wasn't waiting for carla actor list to be updated before spawning missing actors
- third commit to fix error when destroying actors, can't iterate through dictionary and delete entries. To reproduce just launch the basic carla_ros_bridge launchfile, wait until all default actors are created, and quit with ctrl-C.
- A similar problem that I did not fix because it was hiding another one that I couldn't fix: when destroying an actor with attached sensor, (there: https://github.com/carla-simulator/ros-bridge/blob/master/carla_ros_bridge/src/carla_ros_bridge/actor_factory.py#L151), an error similar to the previous one is raised. But when it's fixed, the actors are destroyed, but keep being re-created in …
> Fix spawn bug

- carla_ad_agent/launch/carla_ad_agent.launch.py
- carla_ad_agent/src/carla_ad_agent/agent.py
- carla_ad_agent/src/carla_ad_agent/basic_agent.py
- carla_ad_demo/launch/carla_ad_demo.launch.py
- carla_ad_demo/launch/carla_ad_demo_with_scenario.launch.py
- carla_manual_control/launch/carla_manual_control.launch.py
- carla_manual_control/src/carla_manual_control/carla_manual_control.py
- carla_spawn_objects/src/carla_spawn_objects/carla_spawn_objects.py
- fixed bug where manual_control and carla_ad_agent nodes were both renamed 'ego_vehicle' by their respective launchfile. I had to use an `launch.actions.OpaqueFunction` in the launchfiles in order to use the role_name parameter as a string directly in the `launch.LaunchDescription`, their might be a more elegant way to do that but I didn't find it!
- several bugs with parameter `spawn_point_<role_name>`, it was not taking into account.
- fixed topic names and QoSSettings preventing the carla_ad_agent to see the red trafficlights
- also fixed throttle and brake status bar that weren't being updated in pygames
tested in ros1/ros2 and sync/async
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> Fix agent trafficlights

- carla_ackermann_control/package.xml
- carla_ad_agent/package.xml
- carla_ad_demo/package.xml
- carla_common/package.xml
- carla_manual_control/package.xml
- carla_ros_bridge/package.xml
- carla_ros_scenario_runner/package.xml
- carla_ros_scenario_runner_types/package.xml
- carla_spawn_objects/package.xml
- carla_walker_agent/package.xml
- carla_waypoint_publisher/package.xml
Running `rosdep install -y --from-paths src --ignore-src` command on ros2 branch gives errors:
```
ERROR: the following packages/stacks could not have their rosdep keys resolved to system dependencies:
carla_waypoint_publisher: Cannot locate rosdep definition for [ament_python]
carla_ros_scenario_runner_types: Cannot locate rosdep definition for [message_runtime]
carla_ad_agent: Cannot locate rosdep definition for [ament_python]
carla_ad_demo: Cannot locate rosdep definition for [ament_python]
carla_ackermann_control: Cannot locate rosdep definition for [ament_python]
carla_common: Cannot locate rosdep definition for [ament_python]
carla_spawn_objects: Cannot locate rosdep definition for [ament_python]
carla_manual_control: Cannot locate rosdep definition for [ament_python] …
```
> Fixed rosdep installation errors for missing ros2 packages

- carla_ros_scenario_runner/src/carla_ros_scenario_runner/application_runner.py
Option to give a simple string with the complete cmd line to be executed to application runner. Simpler than a list of every word of the command.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/481)
> application runner can take simple string as argument list

- rviz_carla_plugin/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/488)
> Removed redundant CXX-Standard in CARLA-RViz-Plugin

- .github/workflows/ci.yml
- Makefile
- packaging/build-deb.sh
- packaging/install_dependencies.sh
Updated CI and debian packaging scripts to take into account ROS2 changes.
*Important*: Debian packaging for ROS2 has been disabled (it wasn't working before). The whole debian packaging pipeline needs to be redesign to build ROS2 debian packages.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/499)
> [ROS2] Debian packages and CI

- carla_ros_scenario_runner/src/carla_ros_scenario_runner/ros_vehicle_control.py
ros_timestamp expects a int value, not a function object...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/501)
> Fix RosVehicleControl.update_waypoints

- carla_ros_bridge/launch/carla_ros_bridge.launch
- carla_ros_bridge/launch/carla_ros_bridge.launch.py
- carla_ros_bridge/src/carla_ros_bridge/ego_vehicle.py
This PR fixes a couple of bugs:
* Subscribing again to the ego vehicle topics in passive mode. For the leaderboard use case, we won't create and `EgoVehicle` object as we will be calling the `bridge` with an empty list of ego vehicle role names.
* Fixed `ego_vehicle_role_name` not being used in ROS1.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/507)
> [ROS2] Fixed bug passive mode ang ego vehicle role names argument

- README.ros2.md
Updated installation process for ROS2 to include the installation of ros dependencies using `rosdep`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/508)
> [ROS2] Updated installation process

- README.ros.md
It is already included in the ROS 2 readme so we should also have this for ROS 1
Closes #512
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/513)
> Include submodules in clone instructions for ROS 1

- carla_spawn_objects/src/carla_spawn_objects/carla_spawn_objects.py
- ros_compatibility/src/ros_compatibility/node.py
This PR fixes a bug when spawning a vehicle with `rolename` other than ego_vehicle.
The issue is only happening with ROS1 and not with ROS2.
* In ROS2, we have the `allow_undeclared_parameters parameter` enabled. This means that if we request a non-existent parameter, we receive `None` (no exception raised).
* In ROS1, if we request a non-existent parameter and the alternative_value is `None`, it raises an error.
The current implementation in the PR solves this and the behavior for both distributions is exactly the same (i.e., if we request a non-existent parameter without an alternative value, it returns `None`).
On the other hand, the `alternative_name` argument has been removed. This argument is currently not used and, moreover, the `get_param` method returns a value and not a …
> Fix bug when spawning a vehicle with rolename other than ego_vehicle

- carla_ros_bridge/src/carla_ros_bridge/vehicle.py
Fixed Mathematical sign error causing markers to show up below ground in rviz.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/575)
> Fixed Mathematical sign error causing markers to show up below ground in rviz.

- pcl_recorder/include/PclRecorder.h
- pcl_recorder/src/PclRecorder.cpp
Since version 1.11 PCL uses std::shared_ptr instead of boost::shared_ptr - https://github.com/PointCloudLibrary/pcl/releases/tag/pcl-1.11.0 
However, ROS1 only allows to use boost::shared_ptr in subscribe function. This MR allows ros-bridge to be used with all PCL versions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/569)
> Explicitly specified boost::shared_ptr for pcl 1.11+ compatibility.

- carla_ros_bridge/src/carla_ros_bridge/actor_factory.py
- carla_ros_bridge/src/carla_ros_bridge/bridge.py
Alternative solution to #571 to avoid the delay of the creation of actors two or more ticks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/576)
> Actor creation synchronization

- carla_ros_bridge/launch/carla_ros_bridge_with_example_ego_vehicle.launch.py
- carla_ros_bridge/test/ros_bridge_client_ros2_test.py
- carla_spawn_objects/launch/carla_example_ego_vehicle.launch.py
- carla_spawn_objects/launch/carla_spawn_objects.launch.py
This PR fixes a bug found in foxy and newer distros that crashes the ROS 2 launch system when an argument with `default_value=''` is not overwritten. For some reason the empty string is internally converted to `None`, which raises the following error 
```
File "/opt/ros/foxy/lib/python3.8/site-packages/launch_ros/utilities/evaluate_parameters.py", line 95, in evaluate_parameter_dict
raise TypeError(
TypeError: Allowed value types are bytes, bool, int, float, str, Sequence[bool], Sequence[int], 
Sequence[float], Sequence[str]. Got <class 'NoneType'>. If the parameter is meant to be a string, 
try wrapping it in launch_ros.parameter_descriptions.ParameterValue(value, value_type=str)
```
Similar problems can be found https://github.com/introlab/rtabmap_ros/issues/725, …
> Remove empty launch args default_value

- CHANGELOG.md
- carla_ad_demo/CMakeLists.txt
- carla_ros_scenario_runner/src/carla_ros_scenario_runner/carla_ros_scenario_runner_node.py
This PR fixes the scenario runner node shutdown for ROS2 Foxy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/629)
> Fixed scenario runner node shutdown
